### PR TITLE
Add simple TS typing

### PR DESCRIPTION
**Pull request by james-camilleri**
Super basic typing added, as per #25.

### CODE REVIEW

**Comment by robinscholz** [comment]
@james-camilleri Thanks for the pull request! Would you be interested in completely converting the plugin to typescript? I’m a bit short on time currently, but could be a worthwile effort.

**Comment by james-camilleri** [comment]
I'll have a look at it. I'm also pretty swamped, but it's only a couple of files so I might be able to squeeze it in somewhere as a break from the bleaker stuff I need to code. I'll let you know!

**Comment by g012** [comment]
Hello,
I have just imported 1.1.2 (latest) version, but it seems index.d.ts is missing from the distribution, and I still get the typescript error about types missing in WebStorm.
Could it be that package.json > "files" array is missing "src/index.d.ts" entry ?

WebStorm

Thank you

**Comment by robinscholz** [comment]
@g012 Thanks, missed this. Should be fixed now!

**Pull request merged**
